# frozen_string_literal: true

# Custom mruby build config, generated by `rake beni:config`.
# ============================================================
#
# Self-contained starting point for tuning the mruby build beyond the
# upstream defaults: a native +host+ build plus a wasm32-wasip1 cross
# build, sharing one set of ABI-bearing defines and one mrbgem
# baseline. Everything in this file is yours to edit — trim the wasi
# sections if you only need a tuned host build, adjust the defines and
# gem lists to your runtime's needs.
#
# Wire it into your Rakefile:
#
#   Beni::Tasks.new do
#     build_config "build_config/mruby.rb"
#
#     target :host
#     target :wasi do
#       toolchain "wasi-sdk"
#     end
#   end
#
# (Drop the +wasi+ target declaration when the cross build goes — its
# wasi-sdk reference goes with it.) The file is `load`ed by mruby's rake when
# +Beni::Builder+ sets +MRUBY_CONFIG+ to its absolute path; vendor
# paths resolve through the +BENI_VENDOR_DIR+ env var the builder
# exports alongside it, and +WASI_SDK_PATH+ overrides the wasi-sdk
# location directly.

# mruby auto-enables its mrbgems lockfile (MRuby::Lockfile's class body
# calls +enable+ on load) and writes it next to MRUBY_CONFIG. Dependency
# pinning is beni's own (future) lock mechanism, not mruby's, so this
# config opts out.
MRuby::Lockfile.disable

# Config-time constants shared across the targets below. Only defined
# on first load, so `load`-ing this file twice in the same process does
# not warn about constant redefinition.
unless defined?(BeniBuildConfig)
  # Config-time constants shared across the targets below.
  module BeniBuildConfig
    # ABI-bearing defines applied to BOTH the host and wasi targets,
    # keeping `mrb_int` width and float boxing identical across them
    # (without MRB_INT32 a 64-bit host defaults to MRB_INT64 while
    # wasm32 stays 32-bit — see mruby's mrbconf.h). The beni crates
    # align themselves automatically: their build script parses the
    # `libmruby.flags.mak` sidecar each build leaves next to the
    # archive, so edits here flow into bindgen without code changes.
    ABI_DEFINES = %w[
      MRB_INT32
      MRB_WORDBOX_NO_INLINE_FLOAT
    ].freeze

    # Core-gem baseline shared by both targets: mruby-compiler (the
    # wrapper's `mrb_load_nstring` needs it) plus the portable core
    # extension gems. No I/O / network / process gems — those do not
    # exist on wasm32-wasip1, and keeping the two targets' gem sets
    # identical keeps the verified surface identical.
    MRBGEM_BASELINE = %w[
      mruby-compiler
      mruby-array-ext
      mruby-enum-ext
      mruby-hash-ext
      mruby-numeric-ext
      mruby-object-ext
      mruby-proc-ext
      mruby-range-ext
      mruby-string-ext
      mruby-sprintf
      mruby-symbol-ext
      mruby-error
      mruby-metaprog
    ].freeze
  end
end

# Config-time constants for the +:wasi+ toolchain definition below.
# Same first-load guard as above.
unless defined?(BeniWasiToolchain)
  # Config-time constants for the +:wasi+ toolchain definition below.
  module BeniWasiToolchain
    # +Beni::Builder+ always exports +BENI_VENDOR_DIR+; the bare
    # +vendor/+ fallback only suits running mruby's rake by hand from a
    # project root (under the builder, pwd is the mruby tree itself).
    VENDOR_DIR = (ENV["BENI_VENDOR_DIR"] || File.expand_path("vendor")).freeze
    WASI_SDK   = (ENV["WASI_SDK_PATH"] || File.join(VENDOR_DIR, "wasi-sdk")).freeze
    WASI_SYSROOT = File.join(WASI_SDK, "share", "wasi-sysroot").freeze

    # The three setjmp/longjmp flags. All three must be present at *both*
    # compile and link stages; missing any one trips wasi-libc's
    # `<setjmp.h>` build-time `#error`.
    SJLJ_FLAGS = [
      "-mllvm", "-wasm-enable-sjlj",
      "-mllvm", "-wasm-use-legacy-eh=false"
    ].freeze

    # Cross-compile target. `wasm32-wasi` is the LLVM triple (same ABI
    # as Rust's `wasm32-wasip1` target); the LLVM-triple form is what
    # clang accepts on the command line.
    WASI_TARGET = "wasm32-wasi"

    # Target / sysroot flags applied to every translation unit AND the
    # link step. Frozen so a stray `<<` in a build block raises instead
    # of silently mutating the shared reference.
    TARGET_FLAGS = [
      "--target=#{WASI_TARGET}",
      "--sysroot=#{WASI_SYSROOT}"
    ].freeze
  end
end

# +:wasi+ toolchain — wasi-sdk absolute tool paths, wasm32-wasi target /
# sysroot flags, the setjmp/longjmp three-flag set, and the GNU archive
# format. (Registration is outside the constant guard but idempotent —
# a second load merely overwrites the registry entry with an identical
# definition.)
MRuby::Toolchain.new(:wasi) do |conf, _params|
  wasi_sdk_bin = File.join(BeniWasiToolchain::WASI_SDK, "bin")

  conf.toolchain :clang

  # ---- Tool commands pinned to wasi-sdk absolute paths -----------------
  conf.cc.command       = File.join(wasi_sdk_bin, "clang")
  conf.cxx.command      = File.join(wasi_sdk_bin, "clang++")
  conf.linker.command   = File.join(wasi_sdk_bin, "clang")
  conf.archiver.command = File.join(wasi_sdk_bin, "llvm-ar")
  # llvm-ar on macOS hosts defaults to Darwin (BSD) archive format,
  # which can fail with "section too large" when the archive contains
  # many wasm objects with long member paths. GNU format uses an
  # extended string table.
  conf.archiver.archive_options = "--format=gnu rs %<outfile>s %<objs>s"

  # ---- Cross-compile target / sysroot ----------------------------------
  conf.cc.flags     << BeniWasiToolchain::TARGET_FLAGS
  conf.cxx.flags    << BeniWasiToolchain::TARGET_FLAGS
  conf.linker.flags << BeniWasiToolchain::TARGET_FLAGS

  # ---- setjmp/longjmp ----------------------------------------------------
  # Apply at compile AND link stages — the three-flag set is non-negotiable.
  conf.cc.flags     << BeniWasiToolchain::SJLJ_FLAGS
  conf.cxx.flags    << BeniWasiToolchain::SJLJ_FLAGS
  conf.linker.flags << BeniWasiToolchain::SJLJ_FLAGS
  conf.linker.libraries << "setjmp" # expands to `-lsetjmp` (wasi-libc libsetjmp.a)
end

# Native host build — full libmruby.a plus the host mrbc the cross build
# borrows. +:gcc+ forces a bare +gcc+ so +Toolchain.guess+ cannot pick
# +:clang+ on macOS and resolve through PATH into wasi-sdk's clang
# (on macOS `gcc` is Apple clang anyway).
MRuby::Build.new("host") do |conf|
  conf.toolchain :gcc

  BeniBuildConfig::ABI_DEFINES.each do |define|
    conf.cc.defines  << define
    conf.cxx.defines << define
  end

  BeniBuildConfig::MRBGEM_BASELINE.each { |gem_name| conf.gem core: gem_name }
  conf.build_mrbc_exec
end

MRuby::CrossBuild.new("wasi") do |conf|
  conf.toolchain :wasi

  BeniBuildConfig::ABI_DEFINES.each do |define|
    conf.cc.defines  << define
    conf.cxx.defines << define
  end

  BeniBuildConfig::MRBGEM_BASELINE.each { |gem_name| conf.gem core: gem_name }
end
