module Beni
  class Configuration
    attr_reader vendor_dir: String
    attr_reader build_config: String?
    attr_reader targets: Array[String]
    attr_reader toolchains: Array[SelectedToolchain]

    def initialize: (vendor_dir: String, build_config: String?, targets: Array[String], toolchains: Array[SelectedToolchain]) -> void

    def mruby_version: () -> String
  end
end
