module Beni
  class Tasks < Rake::TaskLib
    @builder: Builder?
    @vendor_toolchains: Array[Vendor::Toolchain]?

    attr_reader configuration: Configuration

    def initialize: () ?{ () [self: DSL::Context] -> void } -> void

    private

    def builder: () -> Builder

    def vendor_toolchains: () -> Array[Vendor::Toolchain]

    def define: () -> void

    def define_vendor_namespace: () -> void

    def define_vendor_setup_task: () -> void

    def wasi_sdk_selected?: () -> bool

    def define_vendor_clean_tasks: () -> void

    def define_toolchain_tasks: (Vendor::Toolchain toolchain) -> void

    def define_build_task: () -> void

    def define_clean_task: () -> void

    def define_config_task: () -> void

    def mruby_version: () -> String
  end
end
