# frozen_string_literal: true

module BeniCoverage
  # Renders the scanned inventory and coverage tiers into the
  # +docs/api_coverage.md+ markdown: a per-category summary and one
  # section per header, followed by the +Appendix+ sections that sit
  # beside the ratio. +coverage+ answers how the measure sees each
  # symbol; +manifest+ supplies only what is not keyed by C symbol.
  class Report
    include Appendix

    # What the measure knows, so the coverage gate can reject a manifest
    # the render itself has no opinion about.
    attr_reader :coverage

    def initialize(surface:, manifest:, coverage:, version:, linked:)
      @surface = surface
      @coverage = coverage
      @admitted = manifest["admitted"] || {}
      @extensions = manifest["extensions"] || {}
      @formats = manifest["get_args_formats"] || {}
      @version = version
      @linked = linked
    end

    def to_md
      sections = @surface.group_by(&:header).map { |header, entries| header_section(header, entries) }
      blocks = [head_block, *sections, formats_block, admitted_block, extensions_block, unknown_block]
      "#{blocks.compact.join("\n")}\n"
    end

    private

    def head_block
      mode = @linked ? "linked (parsed bindings.rs)" : "heuristic (no staged archive)"
      <<~MD
        # mruby C API Coverage

        <!-- Generated by `rake api:coverage`. Do not edit by hand. -->
        <!-- how each symbol is covered, or why it is outside the measure, is curated in .api_coverage.yml -->

        mruby #{@version} · sys detection: #{mode} · #{outside_note}

        Legend: ✅ covered · — missing · ⊘ outside the measure

        #{summary_table}
      MD
    end

    # How many symbols the measure sets aside, so the Measured column is
    # read against the scanned total rather than mistaken for it.
    def outside_note
      counts = @surface.filter_map { |e| @coverage.exclusion(e.name) }.tally
      return "#{@surface.size} scanned, none outside the measure" if counts.empty?

      "#{@surface.size} scanned · outside the measure: #{counts.map { |k, v| "#{v} #{k}" }.join(", ")}"
    end

    # Measured counts only what the measure holds: a declined or
    # flag-gated symbol leaves both sides of the ratio, so a fully
    # graduated surface reads complete.
    def summary_table
      measured = @surface.reject { |e| @coverage.exclusion(e.name) }
      rows = %i[function macro].map { |kind| summary_row(kind.to_s, measured.select { |e| e.kind == kind }) }
      rows << summary_row("total", measured)
      ["| Category | Measured | sys | typed |", "|----------|---------:|----:|------:|", *rows].join("\n")
    end

    def summary_row(label, entries)
      total = entries.size
      in_sys = entries.count { |e| @coverage.in_sys?(e.name) }
      in_typed = entries.count { |e| @coverage.typed?(e.name) }
      "| #{label} | #{total} | #{pct(in_sys, total)} | #{pct(in_typed, total)} |"
    end

    def pct(count, total)
      return "0 (0%)" if total.zero?

      "#{count} (#{(count * 100.0 / total).round}%)"
    end

    def header_section(header, entries)
      rows = entries.sort_by(&:name).map { |e| symbol_row(e) }
      <<~MD.chomp
        ## #{header}

        | Symbol | Kind | sys | typed | Note |
        |--------|------|:---:|:-----:|------|
        #{rows.join("\n")}
      MD
    end

    def symbol_row(entry)
      kind = entry.kind == :function ? "fn" : "macro"
      typed = @coverage.exclusion(entry.name) ? "⊘" : mark(@coverage.typed?(entry.name))
      "| `#{entry.name}` | #{kind} | #{mark(@coverage.in_sys?(entry.name))} | " \
        "#{typed} | #{@coverage.note(entry.name)} |"
    end

    def mark(covered)
      covered ? "✅" : "—"
    end
  end
end
