# frozen_string_literal: true

module BeniCoverage
  # Renders the scanned inventory and coverage tiers into the
  # +docs/api_coverage.md+ markdown: a per-category summary, one section
  # per header, a Rust-extensions section, and a trailing list of
  # manifest entries that no longer match a scanned symbol. +sys+ is a
  # name list (auto-derived); +manifest+ is the hand-authored doc with
  # +typed+ (symbol => Note) and +extensions+ (item => description) maps.
  class Report
    # Manifest entries that match no scanned symbol — stale names the
    # coverage gate rejects.
    attr_reader :unknown

    def initialize(surface:, sys:, manifest:, version:, linked:)
      @surface = surface
      @sys = sys
      @typed = manifest["typed"] || {}
      @extensions = manifest["extensions"] || {}
      @formats = manifest["get_args_formats"] || {}
      @version = version
      @linked = linked
      @unknown = @typed.keys - surface.map(&:name)
    end

    def to_md
      sections = @surface.group_by(&:header).map { |header, entries| header_section(header, entries) }
      "#{[head_block, *sections, formats_block, extensions_block, unknown_block].compact.join("\n")}\n"
    end

    private

    def head_block
      mode = @linked ? "linked (parsed bindings.rs)" : "heuristic (no staged archive)"
      <<~MD
        # mruby C API Coverage

        <!-- Generated by `rake api:coverage`. Do not edit by hand. -->
        <!-- typed tier is curated in .api_coverage.yml -->

        mruby #{@version} · sys detection: #{mode}

        Legend: ✅ covered · — missing

        #{summary_table}
      MD
    end

    def summary_table
      rows = %i[function macro].map { |kind| summary_row(kind.to_s, @surface.select { |e| e.kind == kind }) }
      rows << summary_row("total", @surface)
      ["| Category | Total | sys | typed |", "|----------|------:|----:|------:|", *rows].join("\n")
    end

    def summary_row(label, entries)
      total = entries.size
      in_sys = entries.count { |e| @sys.include?(e.name) }
      in_typed = entries.count { |e| @typed.key?(e.name) }
      "| #{label} | #{total} | #{pct(in_sys, total)} | #{pct(in_typed, total)} |"
    end

    def pct(count, total)
      return "0 (0%)" if total.zero?

      "#{count} (#{(count * 100.0 / total).round}%)"
    end

    def header_section(header, entries)
      rows = entries.sort_by(&:name).map { |e| symbol_row(e) }
      <<~MD.chomp
        ## #{header}

        | Symbol | Kind | sys | typed | Note |
        |--------|------|:---:|:-----:|------|
        #{rows.join("\n")}
      MD
    end

    def symbol_row(entry)
      kind = entry.kind == :function ? "fn" : "macro"
      typed = @typed.key?(entry.name)
      "| `#{entry.name}` | #{kind} | #{mark(@sys.include?(entry.name))} | " \
        "#{mark(typed)} | #{note_cell(entry.name, typed)} |"
    end

    # The Rust item(s) the typed tier binds, from the manifest Note. A
    # typed entry with no Note is flagged — a ✅ that cannot name its Rust
    # side is an unverified claim, not coverage. A lone symbol is set as
    # code; multi-item / prose Notes are rendered as authored.
    def note_cell(name, typed)
      return "" unless typed

      note = @typed[name].to_s.strip
      return "⚠️ unspecified" if note.empty?

      note.match?(/\A\S+\z/) ? "`#{note}`" : note
    end

    def formats_block
      return nil if @formats.empty?

      rows = @formats.map { |spec, entry| formats_row(spec, entry) }
      <<~MD.chomp
        ## get_args format specifiers

        `mrb_get_args`' format string is a specifier vocabulary — one symbol,
        many capabilities — measured as its own lens. ✅ covered · 🔒 sys.

        | Specifier | Covered | Via |
        |-----------|:-------:|-----|
        #{rows.join("\n")}
      MD
    end

    # A literal `|` specifier is escaped so it does not close the table cell.
    def formats_row(spec, entry)
      cell = spec == "|" ? "\\|" : spec
      status = entry["status"] == "covered" ? "✅" : "🔒"
      "| `#{cell}` | #{status} | #{entry["via"]} |"
    end

    def extensions_block
      return nil if @extensions.empty?

      rows = @extensions.sort.map { |item, desc| "| `#{item}` | #{desc.to_s.strip} |" }
      <<~MD.chomp
        ## Rust extensions

        Rust-native surface with no 1:1 mruby C API — not part of the ratio.

        | Item | Description |
        |------|-------------|
        #{rows.join("\n")}
      MD
    end

    def unknown_block
      return nil if @unknown.empty?

      rows = @unknown.sort.map { |name| "- `#{name}`" }
      <<~MD.chomp
        ## Unknown manifest entries

        Listed in `.api_coverage.yml` but absent from the scanned headers
        (renamed/removed upstream, or a typo):

        #{rows.join("\n")}
      MD
    end

    def mark(covered)
      covered ? "✅" : "—"
    end
  end
end
